### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by druvus** [flexidot-bio/flexidot#2]
Could you please add a license to the repo? I would like to add the tool to Bioconda.

**Comment by molbio-dresden** [comment]
Thank you for pointing this out. We will add a license shortly after checking our libraries.

**Comment by molbio-dresden** [comment]
We went through our libraries (all BSD, except one LGPL), took some outside help, and finally pushed the LGPL-v2.1 license. For the future, we can imagine to remove the most restrictive library and release future FlexiDot versions with a BSD license.
